<a href="https://colab.research.google.com/github/Ramlakhan-123/workshop1/blob/main/Ram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=3
print(a)

3


In [ ]:
b=5
print(b)

5


In [ ]:
students= {
    "name":"ram",
    "class":"2nd year",
    "roll":133
}
print(students)

{'name': 'ram', 'class': '2nd year', 'roll': 133}


In [ ]:
marks=50
if(marks>=30):
  print("pass")
else:
  print("fail")

pass


In [ ]:
marks=[2,3,4,5]
for i in marks:
  print(i,end=" ")


2 3 4 5 

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
total=0
marks=[70,80,90,100]
for m in marks:
  total=total+m
print(total)

340


In [ ]:
def add(a,b):
  return a+b
result=add(10,20)
print(result)

30


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
my_list=[1,2,3,4]
print(my_list)
print(type(my_list))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr +5)

[6 7 8 9]


In [ ]:
arr=np.array([1,2,3,4])
print(np.mean(arr))

2.5


In [ ]:
import pandas as pd
data= {
    "name":["ram","shyam","shivam"],
    "roll":[12,13,14],
    "section":['A','B','C']
}
df = pd.DataFrame(data)
print(df)

     name  roll section
0     ram    12       A
1   shyam    13       B
2  shivam    14       C


In [ ]:
print(df.head())


     name  roll section
0     ram    12       A
1   shyam    13       B
2  shivam    14       C


In [ ]:
print(df.tail())

     name  roll section
0     ram    12       A
1   shyam    13       B
2  shivam    14       C


In [ ]:
print(df.shape)

(3, 3)


In [ ]:
print(df.columns)

Index(['name', 'roll', 'section'], dtype='object')


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     3 non-null      object
 1   roll     3 non-null      int64 
 2   section  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None


In [ ]:
print(df.describe())

       roll
count   3.0
mean   13.0
std     1.0
min    12.0
25%    12.5
50%    13.0
75%    13.5
max    14.0


In [ ]:
print(df["name"])
print(df["roll"])

0       ram
1     shyam
2    shivam
Name: name, dtype: object
0    12
1    13
2    14
Name: roll, dtype: int64


In [ ]:
print(df[["name","roll"]])


     name  roll
0     ram    12
1   shyam    13
2  shivam    14


In [ ]:
print(df[df["roll"]==12])

  name  roll section
0  ram    12       A


In [4]:
with open("/content/sample_data/file1",'w') as f:
    f.write("my first file\n")
    f.write("how are you\n")